import type { Metadata } from "next";
import { Kalam } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { cn } from "@/lib/utils";

const kalam = Kalam({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(kalam.className, `antialiased min-h-dvh`)}>
        <Header />
        <main className="">{children}</main>
      </body>
    </html>
  );
}
