import type { Metadata } from "next";
import { Kalam, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { cn } from "@/lib/utils";

const kalam = Kalam({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  variable: "--font-kalam",
});

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.variable,
          inter.className,
          kalam.variable,
          `flex min-h-dvh flex-col gap-4 antialiased`,
        )}
      >
        <Header />
        <main className="container mx-auto">{children}</main>
      </body>
    </html>
  );
}
